# Configuration for Prevent-Public-Repos

privatizeRepo: true
privatizedIssueTitle: '[CRITICAL2] Public Repos Disabled'
#privatizedIssueBody: 'NOTE: Public Repos are disabled for this organization! Repository was automatically converted to a Private Repo.\n\n'
#warningIssueTitle: '[CRITICAL] Public Repository Created'
#warningIssueBody: 'Please note that this repository is publicly visible to the internet!\n\n'
#ccList: ''
#excludeRepos: []
